# Generated by Django 5.2 on 2025-04-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwtapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='user',
            name='send_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Код подтверждения'),
        ),
        migrations.AddField(
            model_name='user',
            name='time_send',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки кода'),
        ),
    ]
