# Generated by Django 5.2 on 2025-04-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwtapp', '0002_user_phone_user_send_code_user_time_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='refresh_token',
            field=models.TextField(blank=True, null=True, verbose_name='Refresh token'),
        ),
    ]
