# Generated by Django 5.2 on 2025-04-14 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwtapp', '0002_user_avatar_alter_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
