# Generated by Django 4.2.1 on 2025-04-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwtapp', '0003_alter_refreshtoken_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refreshtoken',
            options={'verbose_name': 'Refresh token'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': 'Сессии'},
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='duration',
            field=models.TimeField(),
        ),
    ]
