# Generated by Django 5.2 on 2025-04-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwtapp', '0003_remove_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Активная сессия'),
        ),
    ]
