# Generated by Django 4.2.1 on 2025-04-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwtapp', '0004_alter_refreshtoken_options_alter_session_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshtoken',
            name='duration',
            field=models.DateTimeField(),
        ),
    ]
