# Generated by Django 4.2.1 on 2025-04-04 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwtapp', '0005_alter_refreshtoken_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshtoken',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(days=7)),
        ),
    ]
