# Generated by Django 5.2 on 2025-04-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwtapp', '0006_alter_refreshtoken_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refreshtoken',
            name='duration',
        ),
        migrations.AddField(
            model_name='refreshtoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата генерации токена'),
        ),
        migrations.AddField(
            model_name='refreshtoken',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата последнего обновления'),
        ),
    ]
