# Generated by Django 5.2 on 2025-04-05 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwtapp', '0007_remove_refreshtoken_duration_refreshtoken_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refreshtoken',
            options={'verbose_name': 'Refresh token', 'verbose_name_plural': 'Refresh tokens'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': 'Сессия', 'verbose_name_plural': 'Сессии'},
        ),
        migrations.RemoveField(
            model_name='session',
            name='is_active',
        ),
    ]
