# Generated by Django 5.2 on 2025-04-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwtapp', '0008_alter_refreshtoken_options_alter_session_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='user_ip',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Ip устройства пользователя'),
        ),
    ]
