# Generated by Django 5.2 on 2025-04-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwtapp', '0009_session_user_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='user_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Ip устройства пользователя'),
        ),
    ]
