# Generated by Django 5.2 on 2025-04-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwtapp', '0010_alter_session_user_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=550, null=True, verbose_name='Refresh token'),
        ),
        migrations.DeleteModel(
            name='RefreshToken',
        ),
    ]
