# Generated by Django 5.2 on 2025-04-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwtapp', '0011_session_refresh_token_delete_refreshtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='user_ip',
            field=models.GenericIPAddressField(blank=True, null=True, unique=True, verbose_name='Ip устройства пользователя'),
        ),
    ]
