# Generated by Django 5.2 on 2025-04-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwtapp', '0012_alter_session_user_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='device_type',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Тип устройства'),
        ),
    ]
