# Generated by Django 5.2 on 2025-04-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwtapp', '0014_session_created_at_session_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='Сессия закрыта'),
        ),
    ]
