# Generated by Django 5.2 on 2025-04-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwtapp', '0015_session_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='closed',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Сессия закрыта'),
        ),
    ]
