# Generated by Django 5.2 on 2025-04-08 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwtapp', '0016_alter_session_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='closed',
        ),
    ]
