# Generated by Django 5.2 on 2025-04-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwtapp', '0017_remove_session_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Активная сессия'),
        ),
    ]
