# Generated by Django 5.2 on 2025-04-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwtapp', '0018_session_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активная сессия'),
        ),
    ]
