# Generated by Django 5.2 on 2025-04-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwtapp', '0019_alter_session_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='device_type',
            field=models.CharField(blank=True, default='mobile', max_length=150, null=True, verbose_name='Тип устройства'),
        ),
    ]
