# Generated by Django 5.2 on 2025-04-18 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='status',
            new_name='compeleted',
        ),
    ]
