# Generated by Django 5.2 on 2025-04-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0004_taskreceiver_received_alter_taskreceiver_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskreceiver',
            name='received',
        ),
        migrations.AddField(
            model_name='taskreceiver',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
    ]
