# Generated by Django 5.2 on 2025-04-18 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0006_alter_taskreceiver_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskreceiver',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivers', to='mailing_app.task', verbose_name='Задача'),
        ),
    ]
