# Generated by Django 5.2 on 2025-04-18 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0009_alter_taskreceiver_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='compeleted',
            new_name='completed',
        ),
    ]
