# Generated by Django 5.2 on 2025-04-18 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0010_rename_compeleted_task_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskreport',
            old_name='status',
            new_name='task_compeleted',
        ),
    ]
