# Generated by Django 5.2 on 2025-04-19 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0011_rename_status_taskreport_task_compeleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskreport',
            name='task',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='mailing_app.task'),
        ),
    ]
