# Generated by Django 5.2 on 2025-04-19 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0013_alter_taskreport_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskreport',
            name='unsuccessful',
        ),
    ]
