# Generated by Django 5.2 on 2025-04-21 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0014_remove_taskreport_unsuccessful'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskreceiver',
            name='is_active',
        ),
    ]
