# Generated by Django 5.2 on 2025-04-21 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0015_remove_taskreceiver_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил задачу'),
        ),
        migrations.AlterField(
            model_name='taskreport',
            name='successful',
            field=models.PositiveIntegerField(verbose_name='Успешные'),
        ),
        migrations.AlterField(
            model_name='taskreport',
            name='total_receivers',
            field=models.PositiveIntegerField(verbose_name='Общее кол-во получателей'),
        ),
    ]
