# Generated by Django 5.2 on 2025-04-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0016_alter_task_updated_by_alter_taskreport_successful_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskreceiver',
            name='received_message',
            field=models.BooleanField(default=False, verbose_name='Получил сообщение'),
        ),
    ]
