# Generated by Django 5.2 on 2025-04-21 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0017_taskreceiver_received_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskreceiver',
            name='received_message',
        ),
    ]
