# Generated by Django 5.2 on 2025-04-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0018_remove_taskreceiver_received_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskreport',
            name='error_detail',
            field=models.CharField(blank=True, null=True, verbose_name='Описание ошибки'),
        ),
    ]
