# Generated by Django 5.2 on 2025-04-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0019_taskreport_error_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(blank=True, null=True, verbose_name='Название задачи'),
        ),
    ]
