"""
Django settings for project_jwt project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

import os
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-hmsisovuca)#1m@4#q=y_d%a&6ll$qrr+!5(zc(uj_lc8lw+)4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'jwtapp',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project_jwt.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project_jwt.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'postgres',
#         'USER': 'postgres',
#         'PASSWORD': 'mypassword',
#         'HOST': 'my-postgres',
#         'PORT': '5432',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = "jwtapp.User"


REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ],

    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'jwtapp.authentication.JWTAuthentication',
    ]

}


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


TOKEN_AUTH_HEADER = 'Bearer'


load_dotenv()

ACCESS_TOKEN_SECRET_KEY = os.getenv('ACCESS_TOKEN_SECRET_KEY')
REFRESH_TOKEN_SECRET_KEY = os.getenv('REFRESH_TOKEN_SECRET_KEY')

HS256_ALGORITHM = 'HS256'
RS256_ALGORITHM = 'RS256'

ALGORITHMS = HS256_ALGORITHM


# PRIVATE_KEY = os.getenv('PRIVATE_KEY')
# PUBLIC_KEY = os.getenv('PUBLIC_KEY')

PRIVATE_KEY = b'-----BEGIN RSA PRIVATE KEY-----\nMIIEogIBAAKCAQEAqikoCSSbqxzk+TdmnkcaV04Ufi3GVlPUylQyiR1+ApzMqNRr\nvJQy/MHRnBqURpvNyInOQOJkUmF7mT4IyssYh0N1K8BBSHjp3EDppaQ7DFZiVWoT\nePU8j55PHFKVDovt5AGc4Sq+R8rY8UgJ1RRjxj+jyPze6XTspMnk0TY+pfzNIP3N\npzWs16cvCslpFiVtgMUJJTENwyFhoEeMI+zD55QXgy4e5JBPkZ9rAfUBll6PjuQ7\nR+RquHG7U4vte/2e5hwn505Wo0XV+LVuZGf3JRkqcv7TRlic8LUkxGgcxDkJxkXL\nDtB7Z8qatsZW7C+R5n8t2SxL8Mm5YU99hLmcHQIDAQABAoIBAAw+Xd60JaDp7IfW\n6dyMEGPyMemwvX6xe+dhdSlsiwg0Sn2ZznUi0yOT7QZaDnIHyYZoDZ3/+QJi3uCn\nfnAPeqC9xKaOdNdHUmLb9A1/hBT4YKb1gcuVFo1Dvm/mEuRmQr3CZ/L25ZSHQfwX\nS0drtvb2CU28jdJahjrtOmuoIL95eepgh8KzKWd6IUfhPe1CZSl+HBx39darvAKQ\nUDml3O8zbO+GiWkM+3QEwjfRxb32FiENDSuYwdfLwlJwkpRRvBTmp/Upt6F4wmIt\n3zgLYWV6YL6cHFEti9g091qt0qqdxc2L5xFQwDnuSuhuc6EwisAaBIOlxAPxKxZC\nB9tEMrkCgYEAxK3HIEdsbcbtxNpUVP7tQuLxD7JKHLmig6cKcrUztWcAXEGKR1N8\nyN+PZ7OVrmWJ39zF0NICQ7JRh+gA2CCBATckpvPyiVqNJeoBbiqWl9tFM90IaiO1\n6XxP+XjK5Mjxl7XI3eYuPyfMV6P0IssF3iOr/hpXbEWNktEV3V6+NQ8CgYEA3XvU\n/reutGw8S1ptE3ooa/w4TFj99vPphEYXv/fZbI7YmsMn+K7ZIOJNWGt+Ly4EY71T\nK/NmpTPQemVqG6DI1gsQbfWtlN5iAjhWxFcJH6jowRdWpTdhhY/t7uy96e9mFajx\nw5hNjKVaZbacISuC/4ihS4mMjw5uQb0MtmEhlBMCgYBQrgi1URdFoQkAa5+Ujk69\n1WKV0cldJzlnUCqVC4f+rhYTwj77K2BQ9oRZQe3w8G4yitoK41tScd/IJH/UKOFC\nomBCrGeduKuWFfwoOQg1mxk0QUOmZqfE893KtKZmW5ffaA7SGA54kdbdTMBlVWs+\nyNtRDXU3UQDWbTbO7IKSOQKBgG39ax871NTg02iQdY6woZZO4R55K1YSdysrK+w3\nh5AzuDnTJOyI2GdOOx7n8vg3IBLwGHfBHn54JtZButoRlOtG/1e8JAHEFmQH2n8S\nwgMo/L23e139DL8pZP28L+wW6VlkVvvNjOWF0Eim0Q5f72Q7U+6RVm5MulCHM+L2\nhZhlAoGATUKhw4v9A7CQQgxN9QoM1iVYOT4A/fCaMEF3kiKJdZH+4DuGr45377Nx\nO31AOuisW4jxm6QLp1ohcZpO8cYLBpAU/V5v8/WTq/ai+MyoxQfgAue2Ytf0gPeZ\n8sg/qBC+6h9PpfSPxRSQaequilfve35PkZ1eWKziUpBCIDKHocg=\n-----END RSA PRIVATE KEY-----'

PUBLIC_KEY = b'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCqKSgJJJurHOT5N2aeRxpXThR+LcZWU9TKVDKJHX4CnMyo1Gu8lDL8wdGcGpRGm83Iic5A4mRSYXuZPgjKyxiHQ3UrwEFIeOncQOmlpDsMVmJVahN49TyPnk8cUpUOi+3kAZzhKr5HytjxSAnVFGPGP6PI/N7pdOykyeTRNj6l/M0g/c2nNazXpy8KyWkWJW2AxQklMQ3DIWGgR4wj7MPnlBeDLh7kkE+Rn2sB9QGWXo+O5DtH5Gq4cbtTi+17/Z7mHCfnTlajRdX4tW5kZ/clGSpy/tNGWJzwtSTEaBzEOQnGRcsO0Htnypq2xlbsL5Hmfy3ZLEvwyblhT32EuZwd'



ACCESS_TOKEN_EXPIRE = 600
REFRESH_TOKEN_EXPIRE = (7 * 86400)


EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"


EMAIL_HOST = ''
EMAIL_PORT = ''
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = 'amrmamapiinevknw'
EMAIL_USE_SSL = True

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
SERVER_EMAIL = EMAIL_HOST_USER
EMAIL_ADMIN = EMAIL_HOST_USER
